version: "3.9"

services:
  api:
    build: .
    # собирает образ
    ports:
      - "80:80"
    volumes:
      # передавать данные между контейнерами
      # чтобы контейнеры согласовались
      - ./configs/docker_config.py:/code/configs/default_config.py
        # default_config заменяется на docker_config
    depends_on:
      pg:
        condition: service_healthy
        #  контейнер начнется собираться только после того, как проверится, что он в порядке
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
